# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=10, verbose_name='작성자')),
                ('good_points', models.TextField(default=' ', verbose_name='좋았던 점')),
                ('improving_points', models.TextField(default=' ', verbose_name='개선되었으면 하는 점')),
                ('another_points', models.TextField(default=' ', verbose_name='하고싶은 말')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
